baseURL: http://example.org/
languageCode: en-us
title: "Portfolio"
description: "A simple portfolio website."
menu:
  main:
  - name: Projects
    url: /projects/
  - name: Publications
    url: /publications/
  - name: About
    url: /about/
social:
  github: https://github.com/tlynch
  twitter: https://twitter.com/redacted.jeans
